# Builder container
FROM node:16-bullseye AS builder
ENV TZ="Europe/Helsinki"
WORKDIR /opt/app
RUN apt-get update && apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
